
server:
  port: 8080

spring:
  application:
    name: spend-smart
  jpa:
    properties:
      hibernate:
        format_sql: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
