
version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres-container-spend-smart
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: expense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_db_volume_spend_smart
    driver: local